version: "2"
services:
  teacher-pc-server:
    image: cruizba/crecorder-pc-prod
    user: $CURRENT_UID
    privileged: true
    network_mode: host
    environment:
    - DISPLAY=$DISPLAY
    - PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $XDG_RUNTIME_DIR/pulse/native:$XDG_RUNTIME_DIR/pulse/native
    - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    - $PWD/config:$HOME/app/config
    - $PWD/videos:$HOME/app/videos
    - $PWD/data:$HOME/app/data
    - $PWD/temp:$HOME/app/temp
    group_add:
    - $AUDIO_GROUP_CR
    devices:
    - /dev/snd
