version: "2.1"
services:
  teacher-pc-server:
    image: cruizba/crecorder-ci
    privileged: true
    network_mode: "host"
    ports:
      - 8000:8000
    container_name: crecorder-server
    environment:
      - DISPLAY=$DISPLAY
      - PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native
      - TRAVIS_BRANCH=$TRAVIS_BRANCH
    volumes:
      - $PWD/class-recorder:/class-recorder
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XDG_RUNTIME_DIR/pulse/native:$XDG_RUNTIME_DIR/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      - /dev/bus/usb:/dev/bus/usb
    group_add:
      - $AUDIO_GROUP_CR
    devices:
      - /dev/snd

